[tool.poetry]
name = "adp-webscrape"
version = "0.1.0"
description = ""
authors = ["Liam Corbett"]

[tool.poetry.dependencies]
python = "^3.7"
selenium = "^3.141"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
